package com.example.cardissapp.Models

data class DTOEmergencia(
    var id :Int=0,
    var dia: String="",
    var nombreYApellido: String="",
    var edad:String="",
    var domicilio :String="",
    var localidad :String="",
    var grupo :String="",
    var piso :String="",
    var dto :String="",
    var mb :String="",
    var telefono:String="",
    var motivoDeConsulta:String="",
    var ht :String="",
    var hd :String="",
    var hll :String="",
    var hl :String="",
    var hredespacho :String="",
    var motivoRedespacho :String="",
    var codigo:String="",
    var diagnosticoPresuntivo:String="",
    var movil :String="",
    var chofer :String="",
    var medico :String="",
    var observaciones:String="",
    var coseguro:String="",
    var entidad :String="",
    var obrasocial:String="",
    var usuario :String="",
    var latitud : Double=0.0,
    var longitud :Double=0.0,
    var adherente:String="",
    var documento:String="",
    var motivoRedespacho1:String="",
    var debe:Boolean=false,
    var llamado:Boolean=false,
    var zona:String="",
    var plan:String="",
    var diaHl:String="",
    var diaHll:String="",
    var diaHd:String="",
    var diaHt:String="",
    var identidad :Int=0,
    var idPlanEntidad :Int=0,
    var idmedico :Int=0,
    var idchofer :Int=0,
    var coseg :Int=0,
    var cajaCardissId :Int=0,
    var anulada:Boolean=false,
    var motivosAnulacion:String="",
    var diaVisto:String="",
    var cerrada:Boolean=false,
    var orden :Int=0,
    var notificacion:Boolean=false,
    var covid:Boolean=false,
    var fechaAnulacion:String="",


    )
